In [1]:
##Data Preprocessing

In [219]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [206]:
# Importing all Datasets
races_df = pd.read_csv("races.csv", header=[0], encoding="ISO-8859-1")
qualifying_df = pd.read_csv("qualifying.csv", header=[0], encoding="ISO-8859-1")
driver_standings_df = pd.read_csv("driver_standings.csv", header=[0], encoding="ISO-8859-1")
constructor_standings_df = pd.read_csv("constructor_standings.csv", header=[0], encoding="ISO-8859-1")
driver_results_df = pd.read_csv("results.csv", header=[0], encoding="ISO-8859-1")
constructor_results_df = pd.read_csv("constructor_results.csv", header=[0], encoding="ISO-8859-1")

In [207]:
races_list = races_df.loc[:, ['RaceId', 'Year', 'Round', 'CircuitId']]
#REFERENCES: https://stackoverflow.com/questions/15891038/change-data-type-of-columns-in-pandas
races_list = races_list.apply(pd.to_numeric)
races_list.head()

RaceId  Year  Round  CircuitId
0       1  2009      1          1
1       2  2009      2          2
2       3  2009      3         17
3       4  2009      4          3
4       5  2009      5          4

In [216]:
# Select races from 2007 to 2018
race_filter = races_list['Year'].between(2008,2019)
races_list = races_list[race_filter]
print("RACES\n","Shape:", races_list.shape,"and Unique RaceIds:", races_list.RaceId.unique().shape)
races_list.Year.unique()
required_raceIds = races_list.RaceId.unique()
races_list.RaceId.unique()

RACES
 Shape: (233, 4) and Unique RaceIds: (233,)


array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,  337,  338,  339,  340,  341,  342,  343,  344,  345,
        346,  347,  348,  349,  350,  351,  352,  353,  354,  355,  841,
        842,  843,  844,  845,  846,  847,  848,  849,  850,  851,  852,
        853,  854,  855,  856,  857,  858,  859,  860,  861,  862,  863,
        864,  865,  866,  867,  868,  869,  870,  871,  872,  873,  874,
        875,  876,  877,  878,  879,  880,  881,  882,  883,  884,  885,
        886,  887,  888,  890,  891,  892,  893,  894,  895,  896,  897,
        898,  899,  900,  901,  902,  903,  904,  905,  906,  907,  908,
        909,  910,  911,  912,  913,  914,  915,  916,  917,  918,  931,
        932,  929,  930,  928,  926,  927,  933,  934,  936,  937,  938,
        939,  940,  941,  942,  943,  944,  945,  9

In [217]:
qualifying_df.head()
qualifying_data = qualifying_df.loc[:, ['RaceId', 'DriverId', 'ConstructorId', 'QualifyingPosition']]
qualifying_data = qualifying_data.apply(pd.to_numeric)
qualifying_data.RaceId.unique()

array([  18,   19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
         29,   30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
         40,   41,   42,   43,   44,   45,   46,   47,   48,   49,   50,
         51,   52,   53,   54,   55,   56,   57,   58,   59,   60,   61,
         62,   63,   64,   65,   66,   67,   68,   69,   70,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
        104,  109,  125,  140,  156,  158,  160,  161,  173,  175,  176,
        177,  191,  192,  193,  199,  200,  201,  203,  207,  208,  209,
        210,  211,  212,  213,  214,  215,  216,  224,  225,  226,  227,
        228,  229,  230,  240,  241,  242,  243,  244,  245,  246,  247,
        248,  249,  250,  251,  252,  253,  254,  255,  256,  257,  258,
        259,  261,  262,  263,  264,  265,  266,  267,  268,  269,  270,
        271,  272,    1,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   

In [215]:
#Select RaceIds for Races from 2008 to 2019
#REFERECES: https://stackoverflow.com/questions/17071871/how-to-select-rows-from-a-dataframe-based-on-column-values
qualifying_dataset = qualifying_data.loc[qualifying_data['RaceId'].isin(required_raceIds)]
print("QUALIFYING\n","Shape:", qualifying_dataset.shape,"and Unique RaceIds:", qualifying_dataset.RaceId.unique().shape)
qualifying_dataset = qualifying_dataset.sort_values(by=['RaceId', 'DriverId'])
qualifying_dataset.to_csv("QualfyingFiltered.csv")
qualifying_dataset.RaceId.unique()


QUALIFYING
 Shape: (4962, 4) and Unique RaceIds: (232,)


array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,  337,  338,  339,  340,  341,  342,  343,  344,  345,
        346,  347,  348,  349,  350,  351,  352,  353,  354,  355,  841,
        842,  843,  844,  845,  846,  847,  848,  849,  850,  851,  852,
        853,  854,  855,  856,  857,  858,  859,  860,  861,  862,  863,
        864,  865,  866,  867,  868,  869,  870,  871,  872,  873,  874,
        875,  876,  877,  878,  879,  880,  881,  882,  883,  884,  885,
        886,  887,  888,  890,  891,  892,  893,  894,  895,  896,  897,
        898,  899,  900,  901,  902,  903,  904,  905,  906,  907,  908,
        909,  910,  911,  912,  913,  914,  915,  916,  917,  918,  926,
        927,  928,  929,  930,  931,  932,  933,  934,  936,  937,  938,
        939,  940,  941,  942,  943,  944,  945,  9

In [211]:
driver_standings_df['DriverPoints'] = driver_standings_df['DriverPoints'].astype(int)
driver_standings_df.rename(columns={'DriverPoints': 'TotalDriverPoints'}, inplace = True)
driver_standings_data = driver_standings_df.loc[:, ['RaceId', 'DriverId', 'TotalDriverPoints']]
driver_standings_data.head()

RaceId  DriverId  TotalDriverPoints
0      18         1                 10
1      18         2                  8
2      18         3                  6
3      18         4                  5
4      18         5                  4

In [212]:
driver_results_data = driver_results_df.loc[:, ['RaceId', 'DriverId', 'ConstructorId', 'GridNumber', 'DriverPosition']]
driver_results_data.head()

RaceId  DriverId  ConstructorId  GridNumber DriverPosition
0      18         1              1           1              1
1      18         2              2           5              2
2      18         3              3           7              3
3      18         4              4          11              4
4      18         5              1           3              5

In [213]:
driver_results_dataset = driver_results_data.loc[driver_results_data['RaceId'].isin(required_raceIds)]
print("DRIVER RESULTS\n","Shape:", driver_results_dataset.shape,"and Unique RaceIds:", driver_results_dataset.RaceId.unique().shape)
driver_results_dataset = driver_results_dataset.sort_values(by=['RaceId', 'DriverId'])
driver_results_dataset.to_csv("driverResultsFiltered.csv")

DRIVER RESULTS
 Shape: (4985, 5) and Unique RaceIds: (232,)


In [214]:
result = pd.merge(driver_results_dataset, qualifying_dataset, on=['RaceId', 'DriverId'], how='left')
result.to_csv("Resultant Data.csv")

In [172]:
final_dataset = pd.read_csv('Resultant Data.csv')
final_dataset.head()

Unnamed: 0  RaceId  DriverId  ConstructorId  GridNumber DriverPosition  \
0           0       1         1              1          18             \N   
1           1       1         2              2           9             10   
2           2       1         3              3           5              6   
3           3       1         4              4          10              5   
4           4       1         5              1          12             \N   

   QualifyingPosition  
0                  15  
1                  11  
2                   5  
3                  12  
4                  14

In [175]:
new_finalSet = pd.merge(final_dataset, races_list, on = ['RaceId'], how = 'left')
new_finalSet = new_finalSet.iloc[:, [1, 2, 3, 4, 5, 6, 9]]
print("Shape:",new_finalSet.shape)
new_finalSet.head()

Shape: (4585, 7)


RaceId  DriverId  ConstructorId  GridNumber DriverPosition  \
0       1         1              1          18             \N   
1       1         2              2           9             10   
2       1         3              3           5              6   
3       1         4              4          10              5   
4       1         5              1          12             \N   

   QualifyingPosition  CircuitId  
0                  15          1  
1                  11          1  
2                   5          1  
3                  12          1  
4                  14          1

In [244]:
# REFERENCES: https://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns
new_set = pd.merge(new_finalSet, driver_standings_data, on = ['RaceId', 'DriverId'], how = 'left')
new_set.fillna(0, inplace = True)
new_set['TotalDriverPoints'] = new_set['TotalDriverPoints'].astype(int)
new_order = [0,1,2, 3, 5, 6, 7, 4]
new_set = new_set[new_set.columns[new_order]]
new_set.head()

RaceId  DriverId  ConstructorId  GridNumber  QualifyingPosition  CircuitId  \
0       1         1              1          18                  15          1   
1       1         2              2           9                  11          1   
2       1         3              3           5                   5          1   
3       1         4              4          10                  12          1   
4       1         5              1          12                  14          1   

   TotalDriverPoints DriverPosition  
0                  0             \N  
1                  0             10  
2                  3              6  
3                  4              5  
4                  0             \N

In [245]:
dataset_without_points = new_set.iloc[:, 0:7]
dataset_without_points.head()
dataset_without_points.to_csv('DataSetWithoutPoints.csv')

In [246]:
dataset_with_points = new_set
dataset_with_points.to_csv('DataSetWithPoints.csv')
dataset_with_points.head()

RaceId  DriverId  ConstructorId  GridNumber  QualifyingPosition  CircuitId  \
0       1         1              1          18                  15          1   
1       1         2              2           9                  11          1   
2       1         3              3           5                   5          1   
3       1         4              4          10                  12          1   
4       1         5              1          12                  14          1   

   TotalDriverPoints DriverPosition  
0                  0             \N  
1                  0             10  
2                  3              6  
3                  4              5  
4                  0             \N

In [247]:
filterData = dataset_with_points[dataset_with_points['DriverPosition'] != '\\N']
filterData.shape

(3725, 8)

In [258]:
# REFERENCES: https://www.pluralsight.com/guides/importing-and-splitting-data-into-dependent-and-independent-features-for-ml
X = filterData.iloc[:, :-1].values
Y = filterData.iloc[:, -1].values
X_train, X_test, Y_Train, Y_Test = train_test_split(X, Y, test_size=0.1)
print("Train Data:",X_train.shape,"and Test Data:",X_test.shape)

Train Data: (3352, 7) and Test Data: (373, 7)


In [276]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [272]:
lr_model = LogisticRegression()
model = lr_model.fit(X_train, Y_Train)
Y_pred = lr_model.predict(X_test)
#print(Y_pred)

/Users/admin/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/admin/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [291]:
count_misclassified = (Y_Test != Y_pred).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(Y_Test, Y_pred)
print('Accuracy: {:.2f}'.format(accuracy))

Misclassified samples: 311
Accuracy: 0.17
Accuracy: 0.00


In [ ]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, Y_Train) 
dtree_predictions = dtree_model.predict(X_test) 

count_misclassified = (Y_Test != dtree_predictions).sum()
print('Misclassified samples: {}'.format(count_misclassified))
accuracy = metrics.accuracy_score(Y_Test, dtree_predictions)
print('Accuracy: {:.2f}'.format(accuracy))

In [ ]:
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, Y_Train) 
svm_predictions = svm_model_linear.predict(X_test) 

# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, Y_Test)  
print("Accuracy:",accuracy)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 
  
# accuracy on X_test 
accuracy = knn.score(X_test, Y_Test) 
print (accuracy) 
 

In [293]:
from sklearn.naive_bayes import GaussianNB 
gnb = GaussianNB().fit(X_train, Y_Train) 
gnb_predictions = gnb.predict(X_test) 
  
# accuracy on X_test 
accuracy = gnb.score(X_test, Y_Test) 
print (accuracy) 
  

0.17158176943699732
